### ISSUE TITLE
This repo should include just the bare minimum to make p6doc work

### ISSUE THREAD

**Issue by JJ** [noisegul/perl6-p6doc#10]
Excluding documentation itself. It's going to be a problem to merge them eventually, but eventually, what you will want is to have two separate repositories, since it's much better to test p6doc (the tool) separate from perl6/doc (the documents). Also, for  testing it's better to check them on a set of mini-docs (which you and @antoniogamiz) should develop jointly.

**Comment by antoniogamiz** [comment]
I have already started that work in this repo: https://github.com/antoniogamiz/mini-doc. I stopped working on that because first I needed to know all kind of documents that should be in there. In order to do that, I started to refactor `htmlify`, spinning off all processing pod logic to this repo: https://github.com/antoniogamiz/Perl6-Documentable. 

I still have to add the index logic, which has to be separated from the HTML representation. When that module is finished, you will be able to have the same representation (`Perl6::Documentable::Registry`) of the official documentation used to build the docs site. 

I will add some pods to tests all possibilities I have found. You can make a PR to the mini-doc repo or I can add you as a contributor.

**Comment by noisegul** [comment]
@JJ Right now this repository already does use a minimal set of docs derived from the mini-doc repo.
I only temporarily added a few pods to make work easier for now.
Ultimately there won't be any need to *maintain* a /doc folder inside `perl6-p6doc`. And moving (e.g. an even smaller set as testdata) or removing it would not be a problem.

Given this input I again would like to bring up my suggestion of including `mini-doc` as a git submodule and use that for tests down the line. Does anything speak against that?

**Comment by JJ** [comment]
You can use it as a submodule or whatever other procedure you think of, but
my point is that you'll need to work together because as far as I know,
it's not complete.
