### ISSUE TITLE
Use proper indentation in code

### ISSUE THREAD

**Issue by JJ** [noisegul/perl6-p6doc#19]
If you use Comma or some other IDE like that it will get properly indented.

This section, for instance, is not:

https://github.com/noisegul/perl6-p6doc/blob/d068c0b49134138f297fddb12b45568917de1a77/lib/Pod/To/SectionFilter.pm6#L15

**Comment by noisegul** [comment]
Hm I wonder how that one happened, but the reason should not be my choice of editor (`emacs` together with https://github.com/perl6/perl6-mode).

Is anything else not properly indented?

**Comment by JJ** [comment]
I would have to check. emacs does not enforce indentation, you can have
mixed tabs and spaces and it will not blink. The best is to make it show
whitespace and fix on the fly. In general, we prefer no tabs.
There's also a tabs xt test in the perl6 doc repo. You can use it to check
all your files, or add it to a git hook or to the Travis set of tests.

**Comment by noisegul** [comment]
Emacs is however able to untabify (automatically) and can use spaces as tabs, which I use for Perl6.

But in general the repository should not include tabs as I use spaces, so probably leftovers from before, I'll check everything again.

Otherwise using the test you mention would probably the best approach to check it automatically.

**Comment by noisegul** [comment]
Good thing you pointed it out, there's now a test for it.
